2018-06-27 18:10:58,090 ERROR 19126 nodejs.ClusterClientNoResponseError: client no response in 60742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 19126
hostname: wangpantuodeMacBook-Pro.local

2018-06-27 20:55:48,731 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 3176967ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-27 21:58:13,334 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 3704584ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-27 23:58:53,930 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 7220589ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 01:59:54,507 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 7220565ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 03:50:35,860 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 6601331ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 07:52:37,084 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 7220609ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 09:36:15,044 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 6197955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 10:27:41,401 ERROR 23352 [-/127.0.0.1/-/29ms POST /party?userId=123&content=asd] nodejs.TypeError: check enum need array type values
    at Parameter.checkEnum (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_parameter@2.3.0@parameter/index.js:362:11)
    at Parameter.validate (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_parameter@2.3.0@parameter/index.js:92:25)
    at Object.validate (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_egg-validate@1.0.0@egg-validate/app/extend/context.js:12:39)
    at PartyController.create (/Users/peyton/test-workspeace/egg-weapp-2/app/controller/party.js:21:9)
    at Object.callFn (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_egg-core@4.8.0@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_egg-core@4.8.0@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_egg-core@4.8.0@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_egg-core@4.8.0@egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_koa-compose@3.2.1@koa-compose/index.js:44:32)
    at next (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_koa-compose@3.2.1@koa-compose/index.js:45:18)

pid: 23352
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 12:44:40,157 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 190480ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 13:19:07,752 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 2027529ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 13:56:40,713 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 2192924ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

2018-06-28 14:23:19,206 ERROR 22596 nodejs.ClusterClientNoResponseError: client no response in 1578475ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/peyton/test-workspeace/egg-weapp-2/node_modules/_cluster-client@2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
name: 'ClusterClientNoResponseError'
pid: 22596
hostname: wangpantuodeMacBook-Pro.local

